In [1]:
import pandas as pd

# read in CSV files
df1 = pd.read_csv('Resources/books_to_movies.csv')
df2 = pd.read_csv('Resources/Goodreads_books_with_genres.csv')

In [2]:
df1.head()

,Unnamed: 0,Title,Author,Book_Published,Movie_Released
0,0,The Invention of Hugo Cabret,Brian Selznick,2007,2011.0
1,1,My Abandonment,Peter Rock,2009,2018.0
2,2,The Help,Kathryn Stockett,2009,2011.0
3,3,The Cider House Rules,John Irving,1985,1999.0
4,4,David Copperfield,Charles Dickens,1850,2019.0

In [3]:
df2.head()

,Book Id,Title,Author,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,genres
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,"Fantasy;Young Adult;Fiction;Fantasy,Magic;Chil..."
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,"Fantasy;Young Adult;Fiction;Fantasy,Magic;Chil..."
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic,"Fantasy;Fiction;Young Adult;Fantasy,Magic;Chil..."
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,"Fantasy;Fiction;Young Adult;Fantasy,Magic;Chil..."
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic,"Fantasy;Young Adult;Fiction;Fantasy,Magic;Adve..."

In [4]:
# merge t he DataFrames based on "Title" and "Author"
merged_df = pd.merge(df1,df2[['Title', 'Author', 'isbn13']], on=['Title', 'Author'], how='left')
merged_df

,Unnamed: 0,Title,Author,Book_Published,Movie_Released,isbn13
0,0,The Invention of Hugo Cabret,Brian Selznick,2007,2011.0,NaN
1,1,My Abandonment,Peter Rock,2009,2018.0,NaN
2,2,The Help,Kathryn Stockett,2009,2011.0,NaN
3,3,The Cider House Rules,John Irving,1985,1999.0,NaN
4,4,David Copperfield,Charles Dickens,1850,2019.0,NaN
5,5,Charlie and the Chocolate Factory,Roald Dahl,1964,NaN,NaN
6,6,One Flew Over The Cuckoo’s Nest,Ken Kesey,1963,1975.0,NaN
7,7,The Orchid Thief: A True Story of Beauty and O...,Susan Orlean,1998,2002.0,NaN
8,8,Jurassic Park,Michael Crichton,1990,1993.0,9.780345e+12
9,9,The Hate U Give,Angie Thomas,2017,2018.0,NaN
10,10,Dune,Frank Herbert,1965,NaN,NaN
11,11,The Shining,Stephen King,1977,1980.0,9.780450e+12
12,11,The Shining,Stephen King,1977,1980.0,9.780743e+12
13,11,The Shining,Stephen King,1977,1980.0,9.781418e+12
14,12,High Fidelity,Nick Hornby,1995,2000.0,9.781573e+12
15,13,The Lord of the Rings series,J.R.R. Tolkien,NaN,NaN,NaN
16,14,The Chronicles of Narnia,C.S. Lewis,NaN,NaN,NaN
17,15,If Beale Street Could Talk,James Baldwin,1974,2018.0,9.780307e+12
18,16,The Godfather,Mario Puzo,1969,NaN,NaN
19,17,The Glass Castle,Jeannette Walls,2005,2017.0,9.780743e+12
20,18,To Kill a Mockingbird,Harper Lee,1960,1962.0,9.780061e+12
21,18,To Kill a Mockingbird,Harper Lee,1960,1962.0,9.780061e+12
22,19,The Princess Bride: S. Morgenstern’s Classic T...,William Goldman,1973,1987.0,NaN
23,20,Wild: From Lost to Found on the Pacific Crest ...,Cheryl Strayed,2012,2014.0,NaN
24,21,Atonement,Ian McEwan,2003,2007.0,9.780099e+12
25,22,Life of Pi,Yann Martel,2001,2012.0,9.780156e+12
26,23,Push,Sapphire,1996,2009.0,NaN
27,24,12 Years A Slave,Solomon Northup,1853,2013.0,NaN
28,25,Fight Club,Chuck Palahniuk,1996,1999.0,9.780393e+12
29,26,Crazy Rich Asians,Kevin Kwan,2013,2018.0,NaN
30,27,Call Me By Your Name,André Aciman,2007,2017.0,NaN
31,28,Anna Karenina,Leo Tolstoy,1878,2012.0,NaN
32,29,Brokeback Mountain,Annie Proulx,1997,2005.0,9.780743e+12
33,30,The Color Purple,Alice Walker,1982,1985.0,9.780672e+12
34,31,The BFG,Roald Dahl,1982,2016.0,NaN
35,32,The Great Gatsby,F. Scott Fitzgerald,1925,2013.0,9.780141e+12
36,32,The Great Gatsby,F. Scott Fitzgerald,1925,2013.0,9.780892e+12
37,33,The Hours,Michael Cunningham,1998,2002.0,NaN
38,34,Revolutionary Road,Richard Yates,1961,2008.0,NaN
39,35,The Lost Child of Philomena Lee,Martin Sixsmith,1955,2013.0,NaN
40,36,Alice’s Adventures in Wonderland,Lewis Carroll,1865,2010.0,NaN
41,37,Little Women,Louisa M. Alcott,1868–1869,2019.0,NaN
42,38,Pride and Prejudice,Jane Austen,1813,1995.0,9.780193e+12
43,38,Pride and Prejudice,Jane Austen,1813,1995.0,9.780709e+12
44,39,Pride and Prejudice,Jane Austen,1813,2005.0,9.780193e+12
45,39,Pride and Prejudice,Jane Austen,1813,2005.0,9.780709e+12
46,40,The Picture of Dorian Gray,Oscar Wilde,1891,1945.0,9.781557e+12
47,40,The Picture of Dorian Gray,Oscar Wilde,1891,1945.0,9.781421e+12
48,41,The Picture of Dorian Gray,Oscar Wilde,1891,2009.0,9.781557e+12
49,41,The Picture of Dorian Gray,Oscar Wilde,1891,2009.0,9.781421e+12

In [5]:
merged_df.dtypes

Unnamed: 0          int64
Title              object
Author             object
Book_Published     object
Movie_Released    float64
isbn13            float64
dtype: object

In [12]:
merged_df['Movie_Released'] = pd.to_numeric(merged_df['Movie_Released'], errors='coerce').astype('Int64')
merged_df['isbn13'] = pd.to_numeric(merged_df['isbn13'], errors='coerce').astype('Int64')
merged_df

,Unnamed: 0,Title,Author,Book_Published,Movie_Released,isbn13
0,0,The Invention of Hugo Cabret,Brian Selznick,2007,2011,<NA>
1,1,My Abandonment,Peter Rock,2009,2018,<NA>
2,2,The Help,Kathryn Stockett,2009,2011,<NA>
3,3,The Cider House Rules,John Irving,1985,1999,<NA>
4,4,David Copperfield,Charles Dickens,1850,2019,<NA>
5,5,Charlie and the Chocolate Factory,Roald Dahl,1964,<NA>,<NA>
6,6,One Flew Over The Cuckoo’s Nest,Ken Kesey,1963,1975,<NA>
7,7,The Orchid Thief: A True Story of Beauty and O...,Susan Orlean,1998,2002,<NA>
8,8,Jurassic Park,Michael Crichton,1990,1993,9780345418951
9,9,The Hate U Give,Angie Thomas,2017,2018,<NA>
10,10,Dune,Frank Herbert,1965,<NA>,<NA>
11,11,The Shining,Stephen King,1977,1980,9780450040184
12,11,The Shining,Stephen King,1977,1980,9780743437493
13,11,The Shining,Stephen King,1977,1980,9781417618255
14,12,High Fidelity,Nick Hornby,1995,2000,9781573228213
15,13,The Lord of the Rings series,J.R.R. Tolkien,NaN,<NA>,<NA>
16,14,The Chronicles of Narnia,C.S. Lewis,NaN,<NA>,<NA>
17,15,If Beale Street Could Talk,James Baldwin,1974,2018,9780307275936
18,16,The Godfather,Mario Puzo,1969,<NA>,<NA>
19,17,The Glass Castle,Jeannette Walls,2005,2017,9780743247542
20,18,To Kill a Mockingbird,Harper Lee,1960,1962,9780060935467
21,18,To Kill a Mockingbird,Harper Lee,1960,1962,9780061205699
22,19,The Princess Bride: S. Morgenstern’s Classic T...,William Goldman,1973,1987,<NA>
23,20,Wild: From Lost to Found on the Pacific Crest ...,Cheryl Strayed,2012,2014,<NA>
24,21,Atonement,Ian McEwan,2003,2007,9780099429791
25,22,Life of Pi,Yann Martel,2001,2012,9780156030205
26,23,Push,Sapphire,1996,2009,<NA>
27,24,12 Years A Slave,Solomon Northup,1853,2013,<NA>
28,25,Fight Club,Chuck Palahniuk,1996,1999,9780393327342
29,26,Crazy Rich Asians,Kevin Kwan,2013,2018,<NA>
30,27,Call Me By Your Name,André Aciman,2007,2017,<NA>
31,28,Anna Karenina,Leo Tolstoy,1878,2012,<NA>
32,29,Brokeback Mountain,Annie Proulx,1997,2005,9780743271325
33,30,The Color Purple,Alice Walker,1982,1985,9780671727796
34,31,The BFG,Roald Dahl,1982,2016,<NA>
35,32,The Great Gatsby,F. Scott Fitzgerald,1925,2013,9780140620184
36,32,The Great Gatsby,F. Scott Fitzgerald,1925,2013,9780891906797
37,33,The Hours,Michael Cunningham,1998,2002,<NA>
38,34,Revolutionary Road,Richard Yates,1961,2008,<NA>
39,35,The Lost Child of Philomena Lee,Martin Sixsmith,1955,2013,<NA>
40,36,Alice’s Adventures in Wonderland,Lewis Carroll,1865,2010,<NA>
41,37,Little Women,Louisa M. Alcott,1868–1869,2019,<NA>
42,38,Pride and Prejudice,Jane Austen,1813,1995,9780192802385
43,38,Pride and Prejudice,Jane Austen,1813,1995,9780708982280
44,39,Pride and Prejudice,Jane Austen,1813,2005,9780192802385
45,39,Pride and Prejudice,Jane Austen,1813,2005,9780708982280
46,40,The Picture of Dorian Gray,Oscar Wilde,1891,1945,9781557424297
47,40,The Picture of Dorian Gray,Oscar Wilde,1891,1945,9781420925289
48,41,The Picture of Dorian Gray,Oscar Wilde,1891,2009,9781557424297
49,41,The Picture of Dorian Gray,Oscar Wilde,1891,2009,9781420925289

In [14]:
merged_df = merged_df.drop(columns=['Unnamed: 0'])

In [15]:
merged_df.head()

,Title,Author,Book_Published,Movie_Released,isbn13
0,The Invention of Hugo Cabret,Brian Selznick,2007,2011,<NA>
1,My Abandonment,Peter Rock,2009,2018,<NA>
2,The Help,Kathryn Stockett,2009,2011,<NA>
3,The Cider House Rules,John Irving,1985,1999,<NA>
4,David Copperfield,Charles Dickens,1850,2019,<NA>

In [17]:
# export merged_df as csv
merged_df.to_csv('Resources/cleaned_books_to_movies.csv', index=False)